# - name: add user for tests
#   user:
#     name: '{{ username }}'
#     state: present
#     shell: /bin/bash

- name: check user
  shell: awk -F ":" '{print $1}' /etc/passwd | grep '{{ username }}'
  register: user_exists
  ignore_errors: yes

- name: configure user
  when: user_exists.stdout == '{{ username }}'
  block:

    - name: change password
      when: password != False
      user:
        name: '{{ username }}'
        password: '{{ password }}'

    - name: add in sudo
      when: sudo == True
      user: 
        name: '{{ username }}'
        groups: sudo
        append: True

    - name: add in sudoers
      when: sudoers != False
      community.general.sudoers:
        name: custom_sudo
        state: present
        user: '{{ username }}'
        commands: '{{ sudoers }}'
        nopassword: True

    - name: copy pub ssh key
      when: ssh_key != False
      ansible.posix.authorized_key:
        user: '{{ username }}'
        key: "{{ public_key }}"
        state: present
